[package]
name = "yakuake-skin-generator"
version = "1.2.1"
description = "Create, customize, and install custom Yakuake terminal skins"
authors = ["sanguine6660"]
edition = "2021"

[lib]
name = "yakuake_skin_generator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
clap = { version = "4", features = ["derive"] }
tar = "0.4"
flate2 = "1"
tauri-plugin-dialog = "2.7.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
