//! Golden-file contract tests: the Rust generator must stay byte-identical
//! to the TypeScript pipeline. Goldens live in tests/goldens/ and are
//! (re)generated by the TypeScript side:
//!
//!   UPDATE_PARITY_GOLDENS=1 npm run test:parity
//!
//! After an intentional generator change, regenerate the goldens, then run
//! `cargo test` to confirm this suite still passes.

use std::collections::BTreeMap;
use std::path::PathBuf;

const BYTE_PARITY_FILES: [&str; 40] = [
    "parity_skin.colorscheme",
    "LICENSE",
    "README.md",
    "title.skin",
    "tabs.skin",
    "logo.svg",
    "title/background_center.svg",
    "title/background_left.svg",
    "title/background_right.svg",
    "title/config_up.svg",
    "title/config_over.svg",
    "title/config_down.svg",
    "title/focus_up.svg",
    "title/focus_over.svg",
    "title/focus_down.svg",
    "title/quit_up.svg",
    "title/quit_over.svg",
    "title/quit_down.svg",
    "tabs/background_center.svg",
    "tabs/background_left.svg",
    "tabs/background_right.svg",
    "tabs/tab_selected.svg",
    "tabs/tab_unselected.svg",
    "tabs/tab_selected_left.svg",
    "tabs/tab_selected_middle.svg",
    "tabs/tab_selected_right.svg",
    "tabs/tab_unselected_left.svg",
    "tabs/tab_unselected_middle.svg",
    "tabs/tab_unselected_right.svg",
    "tabs/tab_separator.svg",
    "tabs/lock.svg",
    "tabs/plus_up.svg",
    "tabs/plus_over.svg",
    "tabs/plus_down.svg",
    "tabs/minus_up.svg",
    "tabs/minus_over.svg",
    "tabs/minus_down.svg",
    "tabs/close_up.svg",
    "tabs/close_over.svg",
    "tabs/close_down.svg",
];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests")
}

fn fixture_config() -> yakuake_skin_generator_lib::config::ParsedSkin {
    let path = repo_root().join("fixtures/config.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    yakuake_skin_generator_lib::config::parse_skin_json(&text)
        .unwrap_or_else(|e| panic!("fixture config invalid: {e}"))
}

fn generated_files() -> BTreeMap<String, String> {
    let parsed = fixture_config();
    yakuake_skin_generator_lib::generate::prepare_skin_files(&parsed.config, &|_| None)
}

#[test]
fn rust_output_matches_goldens() {
    let files = generated_files();
    let goldens_dir = repo_root().join("goldens");

    let mut failures: Vec<String> = Vec::new();
    for rel in BYTE_PARITY_FILES {
        let Some(actual) = files.get(rel) else {
            failures.push(format!("missing generated file: {rel}"));
            continue;
        };
        let golden_path = goldens_dir.join(rel);
        let Ok(expected) = std::fs::read_to_string(&golden_path) else {
            failures.push(format!(
                "golden missing: {} — run UPDATE_PARITY_GOLDENS=1 npm run test:parity",
                golden_path.display()
            ));
            continue;
        };
        if actual != &expected {
            failures.push(format!("byte mismatch: {rel}"));
        }
    }

    // The generator may not produce anything beyond the whitelist.
    let extra: Vec<&String> = files
        .keys()
        .filter(|k| !BYTE_PARITY_FILES.contains(&k.as_str()) && k.as_str() != "metadata.json")
        .collect();
    assert!(
        extra.is_empty(),
        "unexpected extra files (update whitelists in both parity suites): {extra:?}"
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
